"""empty message

Revision ID: 68eb6d8a5078
Revises: 
Create Date: 2024-04-02 13:51:50.820635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68eb6d8a5078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_image', sa.String(length=500), nullable=True))
        batch_op.drop_column('game_grade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_grade', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
        batch_op.drop_column('game_image')

    # ### end Alembic commands ###
